package jetbrains.mps.tutorial.calculatrice.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Calculatrice = 0;
  public static final int InputField = 1;
  public static final int InputFieldReference = 2;
  public static final int OutputField = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x882daca414b74170L, 0x873fdb338fe2df5cL);
    builder.put(0x568582ef7ecd428fL, Calculatrice);
    builder.put(0x568582ef7ecd97c6L, InputField);
    builder.put(0x568582ef7ecd97c8L, InputFieldReference);
    builder.put(0x568582ef7ecd97c7L, OutputField);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
