package jetbrains.mps.tutorial.calculatrice.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Calculatrice_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new InputField_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new InputFieldReference_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new OutputField_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new InputFieldReference_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x882daca414b74170L, 0x873fdb338fe2df5cL, 0x568582ef7ecd428fL), MetaIdFactory.conceptId(0x882daca414b74170L, 0x873fdb338fe2df5cL, 0x568582ef7ecd97c6L), MetaIdFactory.conceptId(0x882daca414b74170L, 0x873fdb338fe2df5cL, 0x568582ef7ecd97c8L), MetaIdFactory.conceptId(0x882daca414b74170L, 0x873fdb338fe2df5cL, 0x568582ef7ecd97c7L)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x882daca414b74170L, 0x873fdb338fe2df5cL, 0x568582ef7ecd97c8L)).seal();
}
